name: 'continuous_integration'

on:
  push:
    branches:
    - master
    - users/**
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Stage Prep
      shell: bash
      run: |
        # prepping the Azure Function zipdeploy package
        # https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push

        # create a staging directory
        mkdir build
        
        # copy only azure function artifacts to staging directory
        # cp -r !(.vscode|.gitignore|.terraform|.funcignore|terraform|build) ./build

        rsync -av . ./build/ --exclude=.vscode --exclude=.gitignore --exclude=.terraform --exclude=.funcignore --exclude=terraform --exclude=build

        # output all files in staging directory
        ls -R ./build

    # Would be nice to have a pester test here


    - name: Upload artifact NPM package
      uses: actions/upload-artifact@v1
      with:
        name: node-package
        path: ./build